apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: web-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-deployment
          image: flask-app:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
          - name: AMQP_HOST
            value: rabbitmq-service
          ports:
            - containerPort: 5000
