apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: web-namespace 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: myrabbit.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: rabbitmq-service
            port:
              number: 15672
  - host: mypayload.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: flask-service
            port:
              number: 5000
