apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: web-namespace
spec:
  type: NodePort
  ports:
    - name: http
      port: 15672
      targetPort: 15672
      protocol: TCP
      nodePort: 31672
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 30672
  selector:
    app: rabbitmq
